language : java

services: docker


addons:
  sonarcloud:
    organization: "kaikrk" # the key of the org you chose at step #3
    token:
      secure: "88edb58856a440089d12d0733c3ec28fda0bd1f5"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - cd docker/dev
  - docker-compose up -d
  - cd ../../src
  - mvn clean verify sonar:sonar -Dsonar.projectKey=P9OC -Pcoverage,all-test
